Implemented Issue #97: retrieve all departments
christophtrybek/neomdb pull request #100
Opened 2021-04-08 21:15 UTC by KevinGus

Added functionality "retrieveDepartments" in membersController.
Added API-route "/departments" in membersRoutes.
Added type in membersTypes.
Commented type.
Closes #99

2021-04-09 10:33 UTC, christophtrybek approved these changes
LGTM

2021-04-13 09:29 UTC, LennartRukower requested changes
Currently there are eight departments returned. The department with the id eight means "no department". When do we need the eight department?

2021-04-13 09:29 UTC, LennartRukower commented on server/src/members/membersTypes.ts
> +};
Please add a new line between types.

2021-04-13 16:56 UTC, christophtrybek approved these changes
LGTM

2021-04-15 17:48 UTC, LennartRukower approved these changes
LGTM

2021-04-15 18:01 UTC, merged