#32  server  allow user to change own password
christophtrybek/neomdb pull request #101
Opened 2021-04-09 08:25 UTC by johannesfbraun

2021-04-09 10:44 UTC, christophtrybek requested changes
Please revert the update of the npm dependencies the other part of the code LGTM besides the two minor format issues

2021-04-09 10:44 UTC, christophtrybek commented on server/src/members/membersController.ts
> +  FROM mitglied
```suggestion
    FROM mitglied
```

2021-04-09 10:44 UTC, christophtrybek commented on server/src/members/membersController.ts
> +  WHERE mitglied.name = ?`,
```suggestion
    WHERE mitglied.name = ?`,
```

2021-04-09 10:44 UTC, christophtrybek commented on client/package.json
>    "dependencies": {
Since our test suite is not finished yet i would suggest to refrain from large changes in the dependencies to prevent the introduction of bugs. So for now it should only be acceptable to add new dependencies without updating the existing ones. When the test suite is up and running such changes should be possible.

2021-04-09 13:29 UTC, christophtrybek approved these changes
LGTM

2021-04-13 09:42 UTC, LennartRukower requested changes
This API-route should use the method `PATCH` not `POST`, because it updates an existing resource on the server.
See https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol#Request_methods

2021-04-13 09:42 UTC, LennartRukower commented on server/src/members/membersController.ts
> +
Please delete empty line.

2021-04-13 09:42 UTC, LennartRukower commented on server/src/members/membersTypes.ts
> +export type GetPasswordForValidation = {
Please add a comment.

2021-04-13 12:15 UTC, LennartRukower requested changes
The API-route in membersRoutes.ts wasn't changed. It is still a post method.

2021-04-13 12:15 UTC, LennartRukower commented on client/src/ts/members/ChangePassword.tsx
>        // Post request
This comment is not correct anymore.

2021-04-16 20:02 UTC, LennartRukower approved these changes
LGTM

2021-04-22 13:41 UTC, merged