#15 add member page
christophtrybek/neomdb pull request #109
Opened 2021-06-21 17:33 UTC by LennartRukower

Added the member page, which displays information about a single member.

Closes #15

2021-06-28 15:01 UTC, christophtrybek requested changes

2021-06-28 15:01 UTC, christophtrybek commented on server/src/members/membersController.ts
> +          // Delete the exisitng entries of languages of the specific member
Please add empty line above inline comment to enhance readability

2021-06-28 15:01 UTC, christophtrybek commented on server/src/members/membersController.ts
> +            // To save/update the different languages of the member sql strings are saved into an array
Please add empty line above inline comment to enhance readability

2021-06-28 15:01 UTC, christophtrybek commented on server/src/members/membersController.ts
> +            // To save/update the different languages of the member sql strings are saved into an array
Please add empty line above inline comment to enhance readability

2021-06-28 15:01 UTC, christophtrybek commented on server/src/members/membersController.ts
> +                // Delete the existing entries of edv skills of the specific member
Please add empty line above inline comment to enhance readability

2021-06-28 15:01 UTC, christophtrybek commented on server/src/members/membersController.ts
> +                    // To save/update the different edv skills of the member sql strings are saved into an array
Please add empty line above inline comment to enhance readability

2021-06-28 15:01 UTC, christophtrybek commented on server/src/members/membersController.ts
> +                    // To save/update the different edv skills of the member sql strings are saved into an array
Please add empty line above inline comment to enhance readability

2021-06-28 15:01 UTC, christophtrybek commented on server/src/members/membersController.ts
> +   // Grants access to critical fields for members with permission
Please add empty line above inline comment to enhance readability

2021-06-29 10:47 UTC, LennartRukower commented on client/src/ts/members/member-page/MemberPage.tsx
> +/**
The `mounted` variable is used for clean up in the useEffect Hook, which is a combination of the lifecycle methods componentDidMount and componentDidUpdate.

2021-06-29 13:10 UTC, LennartRukower commented on client/src/ts/utils/dateUtils.ts
> +// Options for formatting dates
To enforce, that the date has the right format and thus can be correctly displayed on the frontend and saved in the database.

2021-06-29 13:59 UTC, LennartRukower commented on server/src/database.ts
> +export const executeMultipleQueries = (queries: string[]) => {
I think I forgot to check that, to be honest.
If one query fails, the other queries are still running through.

2021-06-29 14:09 UTC, LennartRukower commented on server/src/members/membersRoutes.ts
> +router.get("/languages", membersController.retrieveLanguages);
I wanted to make it more modular, thus that the retrieveMember Route doesn't get bloated with many queries and to reuse the data.
But I'm not sure, if languages and edv skills are needed in other components as well.

2021-07-03 09:23 UTC, johannesfbraun commented
Es fehlt noch ein NavLink zu "Meine Seite" (machst du das dann als enhancement?)

2021-07-03 09:58 UTC, johannesfbraun commented on client/src/ts/members/member-page/DisplayMemberDetails.tsx
> +   * Handles the closing of the payment infromation dialog
typo

2021-07-03 12:36 UTC, christophtrybek commented on server/src/database.ts
> +export const executeMultipleQueries = (queries: string[]) => {
Would it be necessary to ensure that every query returned successfully?

2021-07-03 12:40 UTC, christophtrybek commented on server/src/members/membersRoutes.ts
> +router.get("/languages", membersController.retrieveLanguages);
It does not matter whether the retrieveMember route has many queries or there are many single requests. IMHO i would only use separate routes if they get reused. Because modularisation is only advisable if the modules get reused in different positions of the system.

2021-07-03 12:51 UTC, christophtrybek commented on client/src/ts/members/member-page/MemberPage.tsx
> +/**
Got it

2021-07-04 09:25 UTC, LennartRukower commented on server/src/database.ts
> +export const executeMultipleQueries = (queries: string[]) => {
It was my original intention that this function would only succeed if every query succeeded.
Unfortunately, I missed something there.
I'm not quite sure how to solve this at the moment. I will have to take a closer look.

2021-07-04 10:02 UTC, LennartRukower commented on server/src/members/membersRoutes.ts
> +router.get("/languages", membersController.retrieveLanguages);
I understand you point, I originally also wanted integrate everything into the retrieve-member route, but would that make logically sense? 
When making an api-call to retrieve a member, would I expect to also get all languages and edv skills? I would say no.
That was my initial reason for using separate routes. I didn't really make that clear in my first comment.

Is that in our case irrelevant?

2021-07-05 12:16 UTC, christophtrybek approved these changes

2021-07-14 14:50 UTC, johannesfbraun approved these changes
LGTM

2021-07-22 10:41 UTC, KevinGus approved these changes
LGTM

2021-08-03 12:12 UTC, qnewald approved these changes

2021-08-05 09:39 UTC, merged