#92 add data for permission
christophtrybek/neomdb pull request #114
Opened 2021-07-01 22:06 UTC by BorchBe99

Added permissions of all Directors and list of all existing permissions

2021-07-02 09:49 UTC, LennartRukower commented
Please link the corresponding issue in the description or via the "Linked issues"-tab.

2021-07-02 10:04 UTC, LennartRukower requested changes
Good pr, @BorchBe99 !
There are just a few minor issues.

2021-07-02 10:04 UTC, LennartRukower commented on server/src/members/membersRoutes.ts
> +router.get("/permissions-of-members", membersController.retrievePermissionsOfMembers);
Retrieving permissions should not be possible for every member.
Only members with special permissions and roles should be able to retrieve permissions.
This route should be **restricted**!

2021-07-02 10:04 UTC, LennartRukower commented on server/src/members/membersRoutes.ts
> +router.get("/permissions", membersController.retrievePermissions);
Retrieving permissions should not be possible for every member.
Only members with special permissions and roles should be able to retrieve permissions.
This route should be **restricted**!

2021-07-02 10:44 UTC, christophtrybek requested changes
Routes need to be private, this is very important! Please consider indentation in future PRs

2021-07-02 10:44 UTC, christophtrybek commented on server/src/members/membersController.ts
> +export const retrieveCurrentDirectors = (req: Request, res: Response): void => {
What happened here?

2021-07-02 10:44 UTC, christophtrybek commented on server/src/members/membersController.ts
> +export const retrieveDepartments = (req: Request, res: Response): void => {
What happened here?

2021-07-04 09:29 UTC, LennartRukower commented
Please add a label to this pr and a project/milestone.

2021-07-17 21:34 UTC, BorchBe99 commented on server/src/members/membersController.ts
> +export const retrieveCurrentDirectors = (req: Request, res: Response): void => {
Fixed indentation

2021-07-17 21:35 UTC, BorchBe99 commented on server/src/members/membersController.ts
> +export const retrieveDepartments = (req: Request, res: Response): void => {
Fixed indentation

2021-07-20 09:00 UTC, LennartRukower approved these changes
LGTM!

2021-07-27 06:12 UTC, christophtrybek approved these changes
LGTM

2021-07-27 22:57 UTC, merged