#87 save jwt in cookie
christophtrybek/neomdb pull request #115
Opened 2021-07-03 22:00 UTC by LennartRukower

Following changes were made:
- Added cookie support to the backend
- Created a new auth route for logging in, retrieving user data and logging out
- Added proxy support to the frontend
-  Rewrote the checkAuth function for authenticating the user in the frontend

For more information about jwt and why to use cookies see the corresponding issue (#87).

Closes #87

2021-07-04 05:28 UTC, christophtrybek approved these changes
LGTM

2021-07-04 10:40 UTC, qnewald approved these changes
Only small improvements.

2021-07-04 10:40 UTC, qnewald commented on client/src/ts/global/App.tsx
> +import { useEffect } from "react";
Either always use spacing after and before curly brackets or never use spacing.

2021-07-04 10:40 UTC, qnewald commented on server/src/global/auth/authController.ts
> +  expiresIn: 60 * 60, // Expires in 1 hour
For easier developement as well as comfort on release I would increase session time.

2021-07-04 10:40 UTC, qnewald commented on server/src/global/auth/authController.ts
> +  httpOnly: true, // Cookie is onyl accesible via the browser
*only

2021-07-04 10:40 UTC, qnewald commented on server/src/global/auth/authController.ts
> + * Options fot the cookie
*for

2021-07-04 10:40 UTC, qnewald commented on server/src/global/auth/authController.ts
> +      `SELECT mitgliedID, name, passwordHash, GROUP_CONCAT(mitglied_has_berechtigung.berechtigung_berechtigungID) AS permissions
The query is used multiple times, maybe store in a class variable?

2021-07-04 10:49 UTC, KevinGus commented on server/src/global/auth/authRoutes.ts
> + * =======>>> ALL routes after this point are accessible for loged in users only <<<=======
*logged

2021-07-04 10:49 UTC, KevinGus approved these changes

2021-07-05 10:20 UTC, LennartRukower commented on server/src/global/auth/authController.ts
> +      `SELECT mitgliedID, name, passwordHash, GROUP_CONCAT(mitglied_has_berechtigung.berechtigung_berechtigungID) AS permissions
It is not used multiple times, therefor a class variable wouldn't make sense.

2021-07-05 10:38 UTC, christophtrybek commented on server/src/global/auth/authController.ts
> +  expiresIn: 60 * 60 * 10, // Expires in 10 hours
Is this change compatible with the owasp best practices on jwt?

2021-07-05 10:52 UTC, LennartRukower commented on server/src/global/auth/authController.ts
> +  expiresIn: 60 * 60 * 10, // Expires in 10 hours
I couldn't find an explicit best practice regarding expiration time of jwts.
I skimmed the JWT-Handbook but only found following information:

> "**Access tokens** are tokens that give those who have them access to protected resources. These ... are usually short-lived and may have an expiration date embedded in them.
> **Refresh tokens**, on the other hand, allow clients to request new access tokens. ... [These] are usually long-lived."

Because of that I increased the expiration time of the jwt. At least for now.

2021-07-09 09:42 UTC, johannesfbraun requested changes
Only found the login oracle

2021-07-09 09:42 UTC, johannesfbraun commented on server/src/global/auth/authController.ts
> + * Sends an httpOnly cookie to the client and retrieves id, username and corresponding permissions
Fix the responsetime oracle

2021-07-27 06:10 UTC, christophtrybek approved these changes
LGTM

2021-08-03 12:13 UTC, qnewald approved these changes

2021-08-05 09:45 UTC, KevinGus approved these changes
LGTM

2021-08-05 10:38 UTC, LennartRukower commented on server/src/global/auth/authController.ts
> + * Sends an httpOnly cookie to the client and retrieves id, username and corresponding permissions
Fixed by the newest commit.

2021-08-25 10:06 UTC, johannesfbraun approved these changes
LGTM

2021-09-20 17:03 UTC, christophtrybek reviewed
LGTM

2021-10-31 11:57 UTC, merged