Refactored membersRoutes
christophtrybek/neomdb pull request #118
Opened 2021-08-05 09:56 UTC by LennartRukower

Refactored membersRoutes by using authController as middleware inside of the router calls and changing the order of the routes.

Closes #117

2021-08-05 10:37 UTC, christophtrybek requested changes

2021-08-05 10:37 UTC, christophtrybek commented on server/src/members/membersRoutes.ts
>  router.get("/", membersController.retrieveMemberList);
Maybe sort in alphabetical order so the developer can find routes faster

2021-08-06 08:37 UTC, christophtrybek approved these changes
LGTM

2021-09-23 07:33 UTC, johannesfbraun approved these changes
LGTM

2021-10-30 11:45 UTC, merged