Added Headline and Button
christophtrybek/neomdb pull request #51
Opened 2020-04-22 18:08 UTC by BorchBe99

2020-04-22 21:22 UTC, LennartRukower commented
Please consider running tslint or use a tslint IDE extension before submitting to prevent style guide violations like:

- single quotes

- non arrow functions

- trailing whitespace

- missing semicolons

- unused imports

- etc.

2020-04-22 21:23 UTC, LennartRukower commented
You should also link the corresponding issue(s).
_https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue_

2020-04-22 21:25 UTC, LennartRukower commented on client/src/ts/global/NotFound.tsx
> +  */
Please remove unnecessary code (there should be no commented out code).

2020-04-22 21:28 UTC, LennartRukower commented on client/src/ts/global/NotFound.tsx
> +      <span style={{
Don't use inline styling. 
Use the material-ui hook-api: _https://material-ui.com/styles/basics/#hook-api_

2020-04-22 21:31 UTC, LennartRukower commented
The NotFound-page is not mobile responsive! 

**Always develop with mobile in mind (mobile first).**

2020-04-22 21:35 UTC, LennartRukower commented
Also: 

- Always request a review from at least one of the other contributors, when creating a pr

- Please add a little description to your pr

2020-04-24 10:53 UTC, christophtrybek commented on client/src/ts/global/NotFound.tsx
> +  */
Correct

2020-04-24 10:53 UTC, christophtrybek commented on client/src/ts/global/NotFound.tsx
> +      <span style={{
Correct

2020-11-10 21:41 UTC, BorchBe99 commented
- Added mobile friendly scaling
- Fixed inline styling
- Fixed code comments

2020-11-11 06:22 UTC, christophtrybek requested changes
Overall good job some small details need to addressed before merging

2020-11-11 06:22 UTC, christophtrybek commented on client/src/ts/global/NotFound.tsx
> +            {""}
Remove empty string

2020-11-11 06:22 UTC, christophtrybek commented on client/src/ts/global/NotFound.tsx
> +            Bei Problemen bitte melden bei: <a href="mailto:it@studentische-beratung.de">it@studentische-beratung.de</a>
Line length < 100

2020-11-11 06:22 UTC, christophtrybek commented on client/src/ts/global/NotFound.tsx
> +          <Button className={classes.backButton} size="medium" variant="contained" disableElevation href="./">Zurück zum Dashboard</Button>
Line length < 100

2020-11-11 06:22 UTC, christophtrybek commented on client/src/ts/global/NotFound.tsx
> +          <Typography className={classes.pos} color="textSecondary">
Combine this section with the one above into "404: Diese Seite wurde nicht gefunden."

2020-11-11 06:22 UTC, christophtrybek commented on client/src/ts/global/NotFound.tsx
> +        <CardContent>
Please check the correctness of the indentation within this tags

2020-11-11 06:22 UTC, christophtrybek commented on client/src/ts/global/NotFound.tsx
>  import React from "react";
Please Add a descriptive Comment above

2020-11-13 12:21 UTC, BorchBe99 commented on client/src/ts/global/NotFound.tsx
> +        <CardContent>
Could you tell me which specific tag do you mean?

2020-11-13 12:42 UTC, christophtrybek commented on client/src/ts/global/NotFound.tsx
> +        <CardContent>
Sorry i meant the <CardContent> Tag but please make sure that the whole file is correctly indented

2020-11-13 12:50 UTC, BorchBe99 commented on client/src/ts/global/NotFound.tsx
> +        <CardContent>
I've checked it and pushed it.

2020-11-17 21:12 UTC, BorchBe99 commented
My last push should include all requested changes

2020-11-18 07:20 UTC, christophtrybek approved these changes
Good Job 🚀👍🏻

Please consider adding a meaningful Description of the Pull Request in the future.

2020-11-18 22:18 UTC, LennartRukower approved these changes
Good job

2020-11-18 22:24 UTC, merged