#65 implement page bar
christophtrybek/neomdb pull request #67
Opened 2020-09-18 15:10 UTC by LennartRukower

The PageBar displays the name of the page the user is currently at, a help button and page-specific options.
Closes #65 #66

2020-11-10 07:26 UTC, christophtrybek requested changes

2020-11-10 07:26 UTC, christophtrybek commented on client/src/ts/members/MemberOverview.tsx
> +        {/* For testing purposes only */}
Parts for testing only should not be committed

2020-11-10 07:26 UTC, christophtrybek commented on client/src/ts/global/navigation/PageBar.tsx
> +    return (
Please check for correct indentation in function body

2020-11-10 07:26 UTC, christophtrybek commented on client/src/ts/global/navigation/PageBar.tsx
> +  const Options: React.FunctionComponent = () => {
separate components must not be in the same file. Check wether component is really necessary if so separate it if not don't use it

2020-11-10 07:26 UTC, christophtrybek commented on client/src/ts/global/navigation/PageBar.tsx
> +  const Options: React.FunctionComponent = () => {
IMHO this should not be a separate component since the functionality is rather small

2020-11-10 07:26 UTC, christophtrybek commented on client/src/ts/global/navigation/PageBar.tsx
> +  const Help: React.FunctionComponent = () => {
separate components must not be in the same file. Check wether component is really necessary if so separate it if not don't use it

2020-11-10 07:26 UTC, christophtrybek commented on client/src/ts/global/navigation/PageBar.tsx
> +  const Help: React.FunctionComponent = () => {
IMHO this should not be a separate component since the functionality is rather small

2020-11-17 11:07 UTC, LennartRukower commented on client/src/ts/members/MemberOverview.tsx
> +        {/* For testing purposes only */}
I know, but without this part of the code, you wouldn't see, what the component is doing. 
That's why I made this branch a draft.

2020-11-17 16:40 UTC, christophtrybek requested changes
Very Good, please make sure that the indentation throughout the project should be two spaces

2020-11-17 16:40 UTC, christophtrybek commented on client/src/ts/global/navigation/PageBar.tsx
> +/*
Indentation should be two spaces

2021-01-11 17:47 UTC, christophtrybek approved these changes

2021-01-11 17:51 UTC, merged