#53 implement snackbar
christophtrybek/neomdb pull request #78
Opened 2021-01-20 11:24 UTC by BorchBe99

This implementation provides an Interface for a fully consumed Snackbar using notistack.

2021-01-20 12:10 UTC, christophtrybek requested changes
Please check indentation it should only consist of two spaces. Consider using .editorconfig trough an appropriate plugin in your IDE

2021-01-20 19:39 UTC, BorchBe99 commented
I fixed the indentation.

2021-01-28 15:48 UTC, LennartRukower approved these changes
Good job Benji!

2021-01-28 15:48 UTC, LennartRukower commented on client/src/ts/global/CustomSnackbar.tsx
> +interface Props {
Please add a comment to this interface.

2021-01-28 15:48 UTC, LennartRukower commented on client/src/ts/global/CustomSnackbar.tsx
> +const CustomSnackbar = (props: Props) => {
Please add a comment to this component.

2021-02-02 19:34 UTC, BorchBe99 commented on client/src/ts/global/CustomSnackbar.tsx
> +interface Props {
Fixed

2021-02-02 19:34 UTC, BorchBe99 commented on client/src/ts/global/CustomSnackbar.tsx
> +const CustomSnackbar = (props: Props) => {
Fixed

2021-02-09 08:33 UTC, christophtrybek requested changes
Issue with spaces vs tabs still persists

2021-02-09 08:33 UTC, christophtrybek commented on client/src/ts/global/NotFound.tsx
> +    createStyles({
Please use spaces instead of tabs

2021-02-20 10:14 UTC, christophtrybek approved these changes
Good job

2021-02-20 10:15 UTC, merged