Added API Call to retrieve directors
christophtrybek/neomdb pull request #90
Opened 2021-03-04 20:42 UTC by KevinGus

Added api route in membersRoutes. 
Added the functionality of retrieveDirectors in membersController.
Closes #86

2021-03-08 20:51 UTC, LennartRukower requested changes
Good pr!

2021-03-08 20:51 UTC, LennartRukower commented on server/src/members/membersController.ts
> +  .then((result: []) => {
Please add a query result type.
See line 66 for an example: ...(result: membersTypes.GetMembersQueryResult)...

2021-03-19 14:08 UTC, LennartRukower requested changes

2021-03-19 14:08 UTC, LennartRukower commented on server/src/members/membersController.ts
> +    `SELECT mitgliedID, vorname, nachname, geschlecht, kuerzel, bezeichnung_maennlich,bezeichnung_weiblich, von, bis
Please remove trailing whitespace.

2021-03-29 16:51 UTC, christophtrybek approved these changes
LGTM

2021-03-31 12:47 UTC, merged