Added API Call:retrieve all members of departments
christophtrybek/neomdb pull request #91
Opened 2021-03-04 20:59 UTC by KevinGus

Added api route /deparment-members in membersRoutes.
Added the functionality of retrieveDepartmentMembers in membersController.
Closes #84

2021-03-05 12:08 UTC, christophtrybek approved these changes
Nice Job. Looks Good To Me.

2021-03-08 20:39 UTC, LennartRukower requested changes
Very good first pr!

2021-03-17 15:27 UTC, christophtrybek approved these changes
LGTM

2021-03-19 12:35 UTC, LennartRukower requested changes
Please always resolve problems, thrown by TSLint (like trailing whitespaces).
Do you have TSLint activated?

2021-03-19 12:35 UTC, LennartRukower commented on server/src/members/membersController.ts
> +    `SELECT mitgliedID, vorname, nachname, ressort, bezeichnung
Delete trailing whitespace

2021-03-19 12:35 UTC, LennartRukower commented on server/src/members/membersController.ts
> +    WHERE ressort = ressortID AND mitgliedstatus <= 3
Delete trailing whitespace

2021-03-30 13:07 UTC, LennartRukower approved these changes

2021-03-31 11:24 UTC, merged