Implemented Issue #98: retrieve all current directors of departments
christophtrybek/neomdb pull request #99
Opened 2021-04-08 20:56 UTC by KevinGus

Added functionality "retrieveCurrentDirectors" in membersController.
Added API-route "/current-directors" in membersRoutes.
Added type in membersTypes.
Commented types.
Closes #98

2021-04-09 06:27 UTC, johannesfbraun commented on server/src/members/membersController.ts
> +        res.status(404).send("Directors not found");
Wrong status response -> probably is stsatus(500)

2021-04-09 06:46 UTC, johannesfbraun requested changes
Sieht top auf bis auf den einen status code

2021-04-09 10:31 UTC, christophtrybek commented on server/src/members/membersController.ts
> +        res.status(404).send("Directors not found");
404 Is the correct status response since the entity does not exist. 204 should only be used if the server is not expected to return something after completing the request (e.g. request for `PUT` and `DELETE`

2021-04-09 10:32 UTC, christophtrybek approved these changes
LGTM

2021-04-13 09:13 UTC, LennartRukower requested changes

2021-04-13 09:13 UTC, LennartRukower commented on server/src/members/membersController.ts
> +/**
Please add a new line between functions.

2021-04-13 09:13 UTC, LennartRukower commented on server/src/members/membersTypes.ts
> +/**
Please add a new line between types.

2021-04-13 09:13 UTC, LennartRukower commented on server/src/members/membersTypes.ts
> +/**
Please add a new line between types.

2021-04-13 09:13 UTC, LennartRukower commented on server/src/members/membersTypes.ts
> +/**
Please add a new line between types.

2021-04-15 17:59 UTC, LennartRukower approved these changes
Looks good. I just have one question. 
Why is "kuerzel" not part of the retrieved data? Is this not important information?

2021-04-15 17:59 UTC, LennartRukower commented on server/src/members/membersController.ts
> +    `SELECT mitgliedID, vorname, nachname
Isn't there "kuerzel" missing?

2021-04-22 11:43 UTC, KevinGus commented on server/src/members/membersController.ts
> +    `SELECT mitgliedID, vorname, nachname
Yes, that´s right. I added "kuerzel", "bezeichnung_weiblich" and "bezeichnung_maennlich" from "evposten". Also I added the attribute "geschlecht" from "mitglied".

2021-04-22 13:56 UTC, johannesfbraun approved these changes
Conflicts otherwise LGTM

2021-04-23 13:22 UTC, LennartRukower approved these changes
LGTM

2021-04-27 16:56 UTC, christophtrybek approved these changes
LGTM

2021-04-27 18:21 UTC, johannesfbraun approved these changes
LGTM

2021-04-27 18:28 UTC, merged